services:
  - type: web
    name: bone-fracture-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PORT
        value: 10000
